# This is a sample to deploy a milvus cluster in milvus-operator's default configurations.
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  config: {}
  components:
    image: milvusdb/milvus:v2.4.17
    standalone:
      replicas: 1
      serviceType: LoadBalancer
  dependencies:
    msgStreamType: "rocksmq" # or "pulsar"
    etcd:
      inCluster:
        values:
          replicaCount: 1
        deletionPolicy: Delete
        pvcDeletion: true
    storage:
      inCluster:
        values:
          resources:
            requests:
              memory: 100Mi
          persistence:
              size: 20Gi
        deletionPolicy: Delete
        pvcDeletion: true